name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Make gradlew executable
      run: chmod +x gradlew

    - name: Clean Gradle cache (if needed)
      run: |
        if [ -d ~/.gradle/caches ]; then
          rm -rf ~/.gradle/caches/build-cache-*
        fi

    - name: Setup Gradle and build
      uses: gradle/gradle-build-action@v2
      with:
        arguments: assembleDebug
        cache-read-only: false
        gradle-home-cache-cleanup: true

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
